ex:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t64idQ5i7YnWwjL2wXR
    access-key-secret: RipAbu0lRpBYzktjecH6YHPItggux1
    bucket-name: test-2026-08-03
